### PR TITLE
Theme tutorial patch

### PR DESCRIPTION
**Pull request by DirtyF**
@ashmaroli new PR to include your changes

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thanks once again, but the looming issue is that regarding **layout: null** instead of **layout:nil**

**Comment by DirtyF** [comment]
How so?

I changed form `null` to `nil` based on
https://raw.githubusercontent.com/jekyll/jekyll/57fd5f887da1189a16bdfbb982d75f725c38d725/test/source/_posts/2013-01-12-nil-layout.markdown

**Comment by ashmaroli** [comment]
[Comment by Parker](https://github.com/jekyll/jekyll/issues/2730#issuecomment-51872340)

**Comment by ashmaroli** [comment]
the true automated way to test this would be to introduce a `_layouts/nil.html` to our test-suite and see if it gets picked up..

**Comment by ashmaroli** [comment]
You may use the following to locally test `layout: nil` behaviour

```gherkin
# features/layout.feature

Feature: Nil Layout
  As a hacker who likes to render unstyled pages
  I want to be able to render some pages without a layout
  In order to make the pages stand on their own

  Scenario: Use custom layout data
    Given I have a _layouts directory
    And I have a "_layouts/nil.html" file with content:
      """
      {{ content }} scrambler from the nil layout
      """
    And I have an "index.md" page with layout "nil" that contains "page content"
    When I run jekyll build
    Then the "_site/index.html" file should exist
    And I should not see "scrambler from the nil layout" in "_site/index.html"
```

**Comment by DirtyF** [comment]
@ashmaroli your test fail.

**Comment by ashmaroli** [comment]
> your test fail.

ergo `layout: nil` is a valid layout when present

**Comment by DirtyF** [comment]
You're right, reverted back to `null` value, I don't know where I thought I saw that we could use `nil` 😲 

```sh
     Build Warning: Layout 'nil' requested in sitemap.xml does not exist.
```

**Pull request merged**
